from pathlib import Path

from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

OUTPUT_FILE = Path(__file__).resolve().parent / "CLISONIX_Financial_Model_Investor_Ready.xlsx"

NAVY = "1F3A5F"
BLUE = "2E75B6"
LIGHT = "DCE6F1"


def style_header(cell):
    cell.font = Font(bold=True, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor=NAVY)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    thin = Side(style="thin", color="D9D9D9")
    cell.border = Border(left=thin, right=thin, top=thin, bottom=thin)


def style_section_title(cell):
    cell.font = Font(size=13, bold=True, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor=BLUE)
    cell.alignment = Alignment(horizontal="left", vertical="center")


def style_money(cell):
    cell.number_format = '€#,##0'


def style_percent(cell):
    cell.number_format = '0.0%'


def style_int(cell):
    cell.number_format = '#,##0'


def auto_width(ws):
    for col in ws.columns:
        max_len = 0
        col_idx = col[0].column
        col_letter = get_column_letter(col_idx)
        for c in col:
            val = "" if c.value is None else str(c.value)
            if len(val) > max_len:
                max_len = len(val)
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 44)


def build_cover(wb):
    ws = wb.active
    ws.title = "Cover"
    ws.merge_cells("A1:F1")
    ws["A1"] = "CLISONIX INVESTOR MODEL — ADVANCED ANALYTICS"
    ws["A1"].font = Font(size=20, bold=True, color="FFFFFF")
    ws["A1"].fill = PatternFill("solid", fgColor=NAVY)
    ws["A1"].alignment = Alignment(horizontal="center")

    ws.merge_cells("A3:F3")
    ws["A3"] = "Board-grade financial model with scenarios, sensitivities, funnel stats, and monthly dynamics"
    ws["A3"].font = Font(size=11)

    ws["A5"] = "Key features"
    ws["A5"].font = Font(bold=True, size=12)
    features = [
        "• 3-year P&L with linked assumptions",
        "• Monthly 2026 forecast (users, MRR, churn, runway)",
        "• Scenario analysis (Bear/Base/Bull)",
        "• Sensitivity matrix (conversion vs churn)",
        "• Detailed unit economics and payback",
        "• Infrastructure efficiency statistics",
    ]
    for idx, f in enumerate(features, start=6):
        ws[f"A{idx}"] = f

    ws["A14"] = "Primary input sheet: Assumptions"
    ws["A15"] = "Generated by: investor-pack/build_investor_excel.py"
    ws["A14"].font = Font(italic=True)
    ws["A15"].font = Font(italic=True)
    auto_width(ws)


def build_assumptions(wb):
    ws = wb.create_sheet("Assumptions")
    ws["A1"] = "Model Assumptions"
    style_section_title(ws["A1"])
    ws.merge_cells("A1:D1")

    headers = ["Input", "2026", "2027", "2028"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=3, column=i, value=h))

    data = [
        ["Total Users", 15420, 45720, 121800],
        ["Paid Users", 600, 3013, 8673],
        ["Average ARPU (monthly)", 16.8, 25.4, 32.8],
        ["Monthly Churn", 0.025, 0.022, 0.018],
        ["Free→Paid Conversion", 0.039, 0.052, 0.071],
        ["CAC", 86, 64, 47],
        ["Infrastructure Monthly", 917, 1489, 2098],
        ["Monthly OPEX", 58417, 90823, 151765],
        ["Monthly Growth (users)", 0.15, 0.11, 0.09],
    ]
    for r, row in enumerate(data, start=4):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    for r in [4, 5, 9, 10, 12]:
        for c in [2, 3, 4]:
            style_int(ws.cell(row=r, column=c))
    for r in [6, 11]:
        for c in [2, 3, 4]:
            ws.cell(row=r, column=c).number_format = '0.0'
    for r in [7, 8, 13]:
        for c in [2, 3, 4]:
            style_percent(ws.cell(row=r, column=c))

    for r in [4, 5, 9, 10, 11]:
        for c in [2, 3, 4]:
            if r in [10, 11]:
                style_money(ws.cell(row=r, column=c))

    ws["A15"] = "Scenario multipliers"
    style_section_title(ws["A15"])
    ws.merge_cells("A15:C15")
    style_header(ws["A16"])
    style_header(ws["B16"])
    style_header(ws["C16"])
    ws["A16"] = "Scenario"
    ws["B16"] = "Revenue Multiplier"
    ws["C16"] = "Cost Multiplier"
    scenarios = [["Bear", 0.80, 1.10], ["Base", 1.00, 1.00], ["Bull", 1.20, 0.95]]
    for i, s in enumerate(scenarios, start=17):
        ws.cell(row=i, column=1, value=s[0])
        ws.cell(row=i, column=2, value=s[1])
        ws.cell(row=i, column=3, value=s[2])
        style_percent(ws.cell(row=i, column=2))
        style_percent(ws.cell(row=i, column=3))

    auto_width(ws)


def build_revenue_model(wb):
    ws = wb.create_sheet("Revenue_Model")
    headers = ["Plan", "Price/Month", "Users 2026", "Users 2027", "Users 2028", "Revenue 2026", "Revenue 2027", "Revenue 2028", "% of 2028"]
    for idx, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=idx, value=h))

    plans = [
        ["Basic", 0, 15000, 45000, 120000],
        ["Pro", 29, 420, 2600, 8300],
        ["Research", 99, 85, 370, 1250],
        ["Enterprise", 499, 6, 20, 48],
        ["API/Developer", 299, 3, 18, 55],
        ["Educational", 199, 8, 25, 70],
    ]

    for r, p in enumerate(plans, start=2):
        for c, val in enumerate(p, start=1):
            ws.cell(row=r, column=c, value=val)
        ws.cell(row=r, column=6, value=f"=B{r}*C{r}*12")
        ws.cell(row=r, column=7, value=f"=B{r}*D{r}*12")
        ws.cell(row=r, column=8, value=f"=B{r}*E{r}*12")

    ws["A9"] = "TOTAL"
    ws["F9"] = "=SUM(F2:F8)"
    ws["G9"] = "=SUM(G2:G8)"
    ws["H9"] = "=SUM(H2:H8)"
    ws["A9"].font = Font(bold=True)

    for r in range(2, 10):
        style_money(ws.cell(row=r, column=2))
        style_money(ws.cell(row=r, column=6))
        style_money(ws.cell(row=r, column=7))
        style_money(ws.cell(row=r, column=8))
    for r in range(2, 9):
        ws.cell(row=r, column=9, value=f"=IF($H$9=0,0,H{r}/$H$9)")
        style_percent(ws.cell(row=r, column=9))

    auto_width(ws)


def build_infrastructure(wb):
    ws = wb.create_sheet("Infrastructure")
    headers = ["Component", "Monthly", "Yearly 2026", "Yearly 2027", "Yearly 2028", "Unit"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    items = [
        ["Hetzner GPU Server (RTX 5090)", 509, "=B2*12", "=B2*12*2", "=B2*12*3", "Core compute"],
        ["Storage + Backups", 258, "=B3*12", "=B3*12", "=B3*12", "Data durability"],
        ["DDoS/Edge Security", 50, "=B4*12", "=B4*12", "=B4*12", "Security"],
        ["Monitoring", 20, "=B5*12", "=B5*12", "=B5*12", "Observability"],
        ["Bandwidth Reserve", 80, "=B6*12", "=B6*12", "=B6*12", "Network"],
    ]
    for r, row in enumerate(items, start=2):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    ws["A8"] = "TOTAL"
    ws["B8"] = "=SUM(B2:B6)"
    ws["C8"] = "=SUM(C2:C6)"
    ws["D8"] = "=SUM(D2:D6)"
    ws["E8"] = "=SUM(E2:E6)"
    ws["A8"].font = Font(bold=True)

    ws["A10"] = "Users"
    ws["B10"] = "=Assumptions!B4"
    ws["C10"] = "=Assumptions!C4"
    ws["D10"] = "=Assumptions!D4"
    ws["A11"] = "Infra Cost per User"
    ws["B11"] = "=IF(B10=0,0,C8/B10)"
    ws["C11"] = "=IF(C10=0,0,D8/C10)"
    ws["D11"] = "=IF(D10=0,0,E8/D10)"

    for r in [2, 3, 4, 5, 6, 8, 11]:
        for c in [2, 3, 4, 5]:
            style_money(ws.cell(row=r, column=c))

    auto_width(ws)


def build_opex(wb):
    ws = wb.create_sheet("OPEX")
    headers = ["Category", "Monthly 2026", "Yearly 2026", "Yearly 2027", "Yearly 2028", "% 2026"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    rows = [
        ["R&D & Development", 28000, "=B2*12", 480000, 720000],
        ["Marketing & Sales", 18500, "=B3*12", 400000, 800000],
        ["Operations", 6500, "=B4*12", 120000, 180000],
        ["Legal & Admin", 3000, "=B5*12", 48000, 60000],
        ["Office & Misc", 1500, "=B6*12", 24000, 36000],
        ["Infrastructure", "=Infrastructure!B8", "=Infrastructure!C8", "=Infrastructure!D8", "=Infrastructure!E8"],
    ]
    for r, row in enumerate(rows, start=2):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    ws["A9"] = "TOTAL"
    ws["B9"] = "=SUM(B2:B7)"
    ws["C9"] = "=SUM(C2:C7)"
    ws["D9"] = "=SUM(D2:D7)"
    ws["E9"] = "=SUM(E2:E7)"
    ws["A9"].font = Font(bold=True)

    for r in range(2, 8):
        ws.cell(row=r, column=6, value=f"=IF($C$9=0,0,C{r}/$C$9)")
        style_percent(ws.cell(row=r, column=6))

    for r in range(2, 10):
        for c in [2, 3, 4, 5]:
            style_money(ws.cell(row=r, column=c))

    auto_width(ws)


def build_pnl(wb):
    ws = wb.create_sheet("PnL_3Y")
    headers = ["Metric", "2026", "2027", "2028", "YoY 2027", "YoY 2028"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    ws["A2"] = "Total Revenue"
    ws["B2"] = "=Revenue_Model!F9"
    ws["C2"] = "=Revenue_Model!G9"
    ws["D2"] = "=Revenue_Model!H9"
    ws["E2"] = "=IF(B2=0,0,C2/B2-1)"
    ws["F2"] = "=IF(C2=0,0,D2/C2-1)"

    ws["A3"] = "Total Expenses"
    ws["B3"] = "=OPEX!C9"
    ws["C3"] = "=OPEX!D9"
    ws["D3"] = "=OPEX!E9"
    ws["E3"] = "=IF(B3=0,0,C3/B3-1)"
    ws["F3"] = "=IF(C3=0,0,D3/C3-1)"

    ws["A4"] = "EBITDA"
    ws["B4"] = "=B2-B3"
    ws["C4"] = "=C2-C3"
    ws["D4"] = "=D2-D3"
    ws["E4"] = "=IF(ABS(B4)<1,0,C4/B4-1)"
    ws["F4"] = "=IF(ABS(C4)<1,0,D4/C4-1)"

    ws["A5"] = "EBITDA Margin"
    ws["B5"] = "=IF(B2=0,0,B4/B2)"
    ws["C5"] = "=IF(C2=0,0,C4/C2)"
    ws["D5"] = "=IF(D2=0,0,D4/D2)"

    for r in [2, 3, 4]:
        for c in [2, 3, 4]:
            style_money(ws.cell(row=r, column=c))
    for c in [5, 6]:
        for r in [2, 3, 4]:
            style_percent(ws.cell(row=r, column=c))
    for c in [2, 3, 4]:
        style_percent(ws.cell(row=5, column=c))

    auto_width(ws)


def build_monthly_forecast_2026(wb):
    ws = wb.create_sheet("Monthly_Forecast_2026")
    headers = ["Month", "Users", "Paid Users", "New Paid", "Churned Paid", "MRR", "Revenue", "COGS(Infra)", "Gross Profit", "Burn", "Runway (months)"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    ws["A2"] = "Jan"
    months = ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    for i, m in enumerate(months, start=3):
        ws.cell(row=i, column=1, value=m)

    ws["B2"] = "=Assumptions!B4"
    ws["C2"] = "=Assumptions!B5"
    ws["D2"] = "=C2*Assumptions!B8"
    ws["E2"] = "=C2*Assumptions!B7"
    ws["F2"] = "=C2*Assumptions!B6"
    ws["G2"] = "=F2"
    ws["H2"] = "=Infrastructure!B8"
    ws["I2"] = "=G2-H2"
    ws["J2"] = "=OPEX!B9-I2"
    ws["K2"] = "=IF(J2<=0,999,600000/J2)"

    for r in range(3, 14):
        ws.cell(row=r, column=2, value=f"=B{r-1}*(1+Assumptions!B12)")
        ws.cell(row=r, column=3, value=f"=C{r-1}+D{r-1}-E{r-1}")
        ws.cell(row=r, column=4, value=f"=B{r}*Assumptions!B8")
        ws.cell(row=r, column=5, value=f"=C{r-1}*Assumptions!B7")
        ws.cell(row=r, column=6, value=f"=C{r}*Assumptions!B6")
        ws.cell(row=r, column=7, value=f"=F{r}")
        ws.cell(row=r, column=8, value="=Infrastructure!B8")
        ws.cell(row=r, column=9, value=f"=G{r}-H{r}")
        ws.cell(row=r, column=10, value=f"=OPEX!B9-I{r}")
        ws.cell(row=r, column=11, value=f"=IF(J{r}<=0,999,600000/J{r})")

    ws["A15"] = "Totals"
    ws["G15"] = "=SUM(G2:G13)"
    ws["J15"] = "=SUM(J2:J13)"
    ws["K15"] = "=AVERAGE(K2:K13)"

    for r in range(2, 16):
        style_int(ws.cell(row=r, column=2))
        style_int(ws.cell(row=r, column=3))
        style_int(ws.cell(row=r, column=4))
        style_int(ws.cell(row=r, column=5))
        style_money(ws.cell(row=r, column=6))
        style_money(ws.cell(row=r, column=7))
        style_money(ws.cell(row=r, column=8))
        style_money(ws.cell(row=r, column=9))
        style_money(ws.cell(row=r, column=10))
        ws.cell(row=r, column=11).number_format = '0.0'

    auto_width(ws)


def build_scenario_analysis(wb):
    ws = wb.create_sheet("Scenario_Analysis")
    headers = ["Scenario", "Revenue 2028", "Expenses 2028", "EBITDA 2028", "EBITDA Margin", "Implied Valuation (8x EBITDA)"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    ws["A2"] = "Bear"
    ws["A3"] = "Base"
    ws["A4"] = "Bull"

    for r, idx in [(2, 17), (3, 18), (4, 19)]:
        ws.cell(row=r, column=2, value=f"=PnL_3Y!D2*Assumptions!B{idx}")
        ws.cell(row=r, column=3, value=f"=PnL_3Y!D3*Assumptions!C{idx}")
        ws.cell(row=r, column=4, value=f"=B{r}-C{r}")
        ws.cell(row=r, column=5, value=f"=IF(B{r}=0,0,D{r}/B{r})")
        ws.cell(row=r, column=6, value=f"=D{r}*8")

    for r in [2, 3, 4]:
        style_money(ws.cell(row=r, column=2))
        style_money(ws.cell(row=r, column=3))
        style_money(ws.cell(row=r, column=4))
        style_percent(ws.cell(row=r, column=5))
        style_money(ws.cell(row=r, column=6))

    auto_width(ws)


def build_sensitivity(wb):
    ws = wb.create_sheet("Sensitivity")
    ws["A1"] = "Sensitivity Matrix: LTV/CAC by Conversion and Churn"
    style_section_title(ws["A1"])
    ws.merge_cells("A1:G1")

    ws["A3"] = "Conv/Churn"
    style_header(ws["A3"])
    churns = [0.015, 0.02, 0.025, 0.03, 0.035]
    convs = [0.03, 0.04, 0.05, 0.06, 0.07]

    for i, c in enumerate(churns, start=2):
        ws.cell(row=3, column=i, value=c)
        style_percent(ws.cell(row=3, column=i))
        style_header(ws.cell(row=3, column=i))

    for i, v in enumerate(convs, start=4):
        ws.cell(row=i, column=1, value=v)
        style_percent(ws.cell(row=i, column=1))
        style_header(ws.cell(row=i, column=1))
        for j in range(2, 7):
            ws.cell(row=i, column=j, value=f"=((Assumptions!B6*0.85)/{get_column_letter(j)}3)/(Assumptions!B10/{i*100})")

    for r in range(4, 9):
        for c in range(2, 7):
            ws.cell(row=r, column=c).number_format = '0.00x'

    auto_width(ws)


def build_unit_economics(wb):
    ws = wb.create_sheet("Unit_Economics")
    headers = ["Metric", "2026", "2027", "2028", "Interpretation"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    rows = [
        ["CAC", "=Assumptions!B10", "=Assumptions!C10", "=Assumptions!D10", "Marketing cost to acquire one paid user"],
        ["ARPU Monthly", "=Assumptions!B6", "=Assumptions!C6", "=Assumptions!D6", "Average paid revenue per month"],
        ["Gross Margin", "=IF(PnL_3Y!B2=0,0,(PnL_3Y!B2-Infrastructure!C8)/PnL_3Y!B2)", "=IF(PnL_3Y!C2=0,0,(PnL_3Y!C2-Infrastructure!D8)/PnL_3Y!C2)", "=IF(PnL_3Y!D2=0,0,(PnL_3Y!D2-Infrastructure!E8)/PnL_3Y!D2)", "Revenue after infra costs"],
        ["Churn", "=Assumptions!B7", "=Assumptions!C7", "=Assumptions!D7", "Monthly paid-user churn"],
        ["LTV", "=IF(B5=0,0,(B3*B4)/B5)", "=IF(C5=0,0,(C3*C4)/C5)", "=IF(D5=0,0,(D3*D4)/D5)", "Lifetime value"],
        ["LTV/CAC", "=IF(B2=0,0,B6/B2)", "=IF(C2=0,0,C6/C2)", "=IF(D2=0,0,D6/D2)", "Unit economics quality"],
        ["Payback (months)", "=IF(B3*B4=0,0,B2/(B3*B4))", "=IF(C3*C4=0,0,C2/(C3*C4))", "=IF(D3*D4=0,0,D2/(D3*D4))", "Time to recover CAC"],
    ]
    for r, row in enumerate(rows, start=2):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    for r in [2, 3, 6]:
        for c in [2, 3, 4]:
            style_money(ws.cell(row=r, column=c))
    for r in [4, 5]:
        for c in [2, 3, 4]:
            style_percent(ws.cell(row=r, column=c))
    for c in [2, 3, 4]:
        ws.cell(row=7, column=c).number_format = '0.00x'
        ws.cell(row=8, column=c).number_format = '0.0'

    auto_width(ws)


def build_use_of_funds(wb):
    ws = wb.create_sheet("Use_of_Funds")
    for i, h in enumerate(["Category", "Amount", "%"], start=1):
        style_header(ws.cell(row=1, column=i, value=h))
    ws["E1"] = "Seed Round"
    ws["F1"] = 600000
    style_money(ws["F1"])

    rows = [
        ["Product Development", 240000],
        ["Marketing Launch", 180000],
        ["Infrastructure", 60000],
        ["Team Expansion", 90000],
        ["Operations & Buffer", 30000],
    ]
    for r, row in enumerate(rows, start=2):
        ws.cell(row=r, column=1, value=row[0])
        ws.cell(row=r, column=2, value=row[1])
        ws.cell(row=r, column=3, value=f"=B{r}/$F$1")
    ws["A8"] = "TOTAL"
    ws["B8"] = "=SUM(B2:B6)"
    ws["C8"] = "=SUM(C2:C6)"
    for r in range(2, 9):
        style_money(ws.cell(row=r, column=2))
        style_percent(ws.cell(row=r, column=3))
    auto_width(ws)


def build_kpis(wb):
    ws = wb.create_sheet("KPIs")
    for i, h in enumerate(["KPI", "Current", "Target 2026", "Target 2028", "Status"], start=1):
        style_header(ws.cell(row=1, column=i, value=h))

    rows = [
        ["MRR", 8500, "=Monthly_Forecast_2026!F2", "=PnL_3Y!D2/12", "tracking"],
        ["Gross Margin", 0.96, "=Unit_Economics!B4", "=Unit_Economics!D4", "good"],
        ["CAC", 52, "=Unit_Economics!B2", "=Unit_Economics!D2", "improving"],
        ["LTV", 180, "=Unit_Economics!B6", "=Unit_Economics!D6", "improving"],
        ["LTV/CAC", 3.5, "=Unit_Economics!B7", "=Unit_Economics!D7", "strong"],
        ["Runway Months", 6, "=Monthly_Forecast_2026!K15", "=Monthly_Forecast_2026!K15", "monitor"],
    ]
    for r, row in enumerate(rows, start=2):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    for r in [2, 4, 5]:
        for c in [2, 3, 4]:
            style_money(ws.cell(row=r, column=c))
    for c in [2, 3, 4]:
        style_percent(ws.cell(row=3, column=c))
    for c in [2, 3, 4]:
        ws.cell(row=6, column=c).number_format = '0.00x'
        ws.cell(row=7, column=c).number_format = '0.0'

    auto_width(ws)


def build_vc_benchmark(wb):
    ws = wb.create_sheet("VC_Benchmark")
    ws["A1"] = "VC Benchmark — Clisonix vs SaaS Median"
    style_section_title(ws["A1"])
    ws.merge_cells("A1:F1")

    headers = ["Metric", "Clisonix 2028", "SaaS Median", "Top Quartile", "Gap vs Median", "Status"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=3, column=i, value=h))

    rows = [
        ["Revenue Growth YoY", "=PnL_3Y!F2", 0.90, 1.40, "=B4-C4", ""],
        ["EBITDA Margin", "=PnL_3Y!D5", 0.15, 0.30, "=B5-C5", ""],
        ["Gross Margin", "=Unit_Economics!D4", 0.78, 0.86, "=B6-C6", ""],
        ["LTV/CAC", "=Unit_Economics!D7", 3.00, 5.00, "=B7-C7", ""],
        ["CAC Payback (months)", "=Unit_Economics!D8", 12.0, 8.0, "=C8-B8", ""],
        ["Churn (monthly)", "=Unit_Economics!D5", 0.030, 0.020, "=C9-B9", ""],
        ["Infra Cost/User", "=Infrastructure!D11", 2.50, 1.20, "=C10-B10", ""],
    ]
    for r, row in enumerate(rows, start=4):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    ws["A12"] = "Weighted Score"
    ws["B12"] = "=SUMPRODUCT(B4:B10/C4:C10,{0.15,0.2,0.15,0.2,0.1,0.1,0.1})"
    ws["C12"] = 1.0
    ws["D12"] = 1.25

    for r in [4, 5, 6, 9]:
        for c in [2, 3, 4, 5]:
            style_percent(ws.cell(row=r, column=c))
    for r in [7]:
        for c in [2, 3, 4, 5]:
            ws.cell(row=r, column=c).number_format = '0.00x'
    for r in [8, 10]:
        for c in [2, 3, 4, 5]:
            ws.cell(row=r, column=c).number_format = '0.0'
            if r == 10:
                style_money(ws.cell(row=r, column=c))

    ws["B12"].number_format = '0.00x'
    ws["C12"].number_format = '0.00x'
    ws["D12"].number_format = '0.00x'

    for r in range(4, 11):
        ws.cell(row=r, column=6, value=f"=IF(B{r}>=D{r},\"Top Quartile\",IF(B{r}>=C{r},\"Above Median\",\"Below Median\"))")

    bar = BarChart()
    bar.title = "Clisonix vs Median (Key Metrics)"
    bar.y_axis.title = "Value"
    data = Reference(ws, min_col=2, min_row=3, max_col=3, max_row=10)
    cats = Reference(ws, min_col=1, min_row=4, max_row=10)
    bar.add_data(data, titles_from_data=True)
    bar.set_categories(cats)
    bar.height = 8
    bar.width = 16
    ws.add_chart(bar, "A14")

    ws["D14"] = "Benchmark Notes"
    style_section_title(ws["D14"])
    ws.merge_cells("D14:F14")
    notes = [
        "Medians are directional early-stage SaaS benchmarks.",
        "Use this sheet for investor narrative, not as audited market data.",
        "Replace medians/top quartile with sector-specific comps when available.",
    ]
    for i, n in enumerate(notes, start=15):
        ws[f"D{i}"] = f"• {n}"

    auto_width(ws)


def build_data_room_ready(wb):
    ws = wb.create_sheet("Data_Room_Ready")
    ws["A1"] = "Data Room Readiness — Investor Due Diligence"
    style_section_title(ws["A1"])
    ws.merge_cells("A1:F1")

    headers = ["Category", "Document / Evidence", "Owner", "Status", "Priority", "Notes"]
    for i, h in enumerate(headers, start=1):
        style_header(ws.cell(row=3, column=i, value=h))

    items = [
        ["Corporate", "Certificate of Incorporation", "Founder", "Pending", "High", "Upload latest signed copy"],
        ["Corporate", "Cap Table (fully diluted)", "Founder", "Pending", "High", "Include options and notes"],
        ["Finance", "3-year Financial Model (this workbook)", "Finance", "Done", "High", "Linked assumptions included"],
        ["Finance", "Bank Statements (last 12 months)", "Finance", "Pending", "Medium", "Mask sensitive account numbers"],
        ["Legal", "Terms of Service + Privacy Policy", "Legal", "Pending", "High", "GDPR alignment required"],
        ["Legal", "IP Assignment Agreements", "Legal", "Pending", "High", "Founders + contractors"],
        ["Product", "Architecture Overview", "CTO", "Done", "Medium", "Include Ocean Core + Excel Core"],
        ["Product", "Roadmap (12-18 months)", "Product", "Pending", "Medium", "Milestones + dependencies"],
        ["Security", "Security Policy + Incident Plan", "Security", "Pending", "High", "Add RTO/RPO targets"],
        ["Security", "Access Control Matrix", "Security", "Pending", "Medium", "Roles and privileges"],
        ["Traction", "User Growth Evidence", "Growth", "Done", "High", "Use product analytics exports"],
        ["Traction", "Retention/Cohort Analysis", "Growth", "Pending", "Medium", "By country and plan"],
        ["Commercial", "Top Customer Contracts", "Sales", "Pending", "High", "Redact confidential pricing if needed"],
        ["Commercial", "Pipeline Forecast", "Sales", "Pending", "Medium", "Weighted opportunities"],
        ["Operations", "SLA/Uptime Evidence", "Ops", "Done", "Medium", "Include monitoring snapshots"],
        ["Operations", "Backup & Disaster Recovery Proof", "Ops", "Pending", "High", "Restore test evidence"],
    ]

    for r, row in enumerate(items, start=4):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    ws["A22"] = "Completion KPIs"
    style_section_title(ws["A22"])
    ws.merge_cells("A22:C22")

    ws["A23"] = "Total Items"
    ws["B23"] = "=COUNTA(A4:A200)"
    ws["A24"] = "Completed (Done)"
    ws["B24"] = "=COUNTIF(D4:D200,\"Done\")"
    ws["A25"] = "Pending"
    ws["B25"] = "=COUNTIF(D4:D200,\"Pending\")"
    ws["A26"] = "Readiness %"
    ws["B26"] = "=IF(B23=0,0,B24/B23)"
    style_percent(ws["B26"])

    ws["D23"] = "High Priority Open"
    ws["E23"] = "=COUNTIFS(E4:E200,\"High\",D4:D200,\"Pending\")"
    ws["D24"] = "Medium Priority Open"
    ws["E24"] = "=COUNTIFS(E4:E200,\"Medium\",D4:D200,\"Pending\")"

    auto_width(ws)


def build_dashboard(wb):
    ws = wb.create_sheet("Dashboard")
    ws["A1"] = "Clisonix Investor Analytics Dashboard"
    style_section_title(ws["A1"])
    ws.merge_cells("A1:F1")

    for i, h in enumerate(["Metric", "2026", "2027", "2028"], start=1):
        style_header(ws.cell(row=3, column=i, value=h))

    rows = [
        ["Revenue", "=PnL_3Y!B2", "=PnL_3Y!C2", "=PnL_3Y!D2"],
        ["Expenses", "=PnL_3Y!B3", "=PnL_3Y!C3", "=PnL_3Y!D3"],
        ["EBITDA", "=PnL_3Y!B4", "=PnL_3Y!C4", "=PnL_3Y!D4"],
        ["EBITDA Margin", "=PnL_3Y!B5", "=PnL_3Y!C5", "=PnL_3Y!D5"],
        ["Paid Users", "=Assumptions!B5", "=Assumptions!C5", "=Assumptions!D5"],
        ["ARPU", "=Assumptions!B6", "=Assumptions!C6", "=Assumptions!D6"],
    ]
    for r, row in enumerate(rows, start=4):
        for c, v in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=v)

    for r in [4, 5, 6, 9]:
        for c in [2, 3, 4]:
            style_money(ws.cell(row=r, column=c))
    for c in [2, 3, 4]:
        style_percent(ws.cell(row=7, column=c))
        style_int(ws.cell(row=8, column=c))

    line = LineChart()
    line.title = "Revenue vs EBITDA"
    line.style = 2
    line.y_axis.title = "EUR"
    line.x_axis.title = "Year"
    data = Reference(ws, min_col=2, min_row=4, max_col=4, max_row=6)
    cats = Reference(ws, min_col=1, min_row=4, max_row=6)
    line.add_data(data, titles_from_data=False, from_rows=True)
    line.set_categories(Reference(ws, min_col=2, min_row=3, max_col=4, max_row=3))
    ws.add_chart(line, "A12")

    bar = BarChart()
    bar.title = "2028 Revenue Mix"
    bar.y_axis.title = "EUR"
    data2 = Reference(wb["Revenue_Model"], min_col=8, min_row=2, max_row=8)
    cats2 = Reference(wb["Revenue_Model"], min_col=1, min_row=2, max_row=8)
    bar.add_data(data2, titles_from_data=False)
    bar.set_categories(cats2)
    ws.add_chart(bar, "D12")

    auto_width(ws)


def main():
    wb = Workbook()
    build_cover(wb)
    build_assumptions(wb)
    build_revenue_model(wb)
    build_infrastructure(wb)
    build_opex(wb)
    build_pnl(wb)
    build_monthly_forecast_2026(wb)
    build_scenario_analysis(wb)
    build_sensitivity(wb)
    build_unit_economics(wb)
    build_use_of_funds(wb)
    build_kpis(wb)
    build_vc_benchmark(wb)
    build_data_room_ready(wb)
    build_dashboard(wb)

    for ws in wb.worksheets:
        ws.freeze_panes = "A2"

    wb.save(OUTPUT_FILE)
    print(f"Generated advanced model: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
