Param(
    [string]$WriteEnv = ""
)

$ErrorActionPreference = "Stop"

$cores = [Environment]::ProcessorCount
if ($cores -le 2) {
    $threads = 1
    $parallel = 1
} elseif ($cores -le 8) {
    $threads = $cores - 1
    $parallel = 1
} else {
    $threads = $cores - 2
    $parallel = 2
}

if ($threads -lt 1) { $threads = 1 }

Write-Host "🔧 CPU-Only tuning profile"
Write-Host "  cores:                 $cores"
Write-Host "  worker threads:        $threads"
Write-Host "  ollama parallel req:   $parallel"
Write-Host ""
Write-Host "Set these env vars (current session):"
Write-Host "  `$env:OMP_NUM_THREADS=$threads"
Write-Host "  `$env:MKL_NUM_THREADS=$threads"
Write-Host "  `$env:OPENBLAS_NUM_THREADS=$threads"
Write-Host "  `$env:NUMEXPR_NUM_THREADS=$threads"
Write-Host "  `$env:UVICORN_WORKERS=1"
Write-Host "  `$env:OLLAMA_NUM_PARALLEL=$parallel"
Write-Host "  `$env:OLLAMA_MAX_LOADED_MODELS=1"
Write-Host "  `$env:OLLAMA_KEEP_ALIVE=30m"

if ($WriteEnv -ne "") {
    @"
# Auto-generated by scripts/cpu_boost_no_gpu.ps1
OMP_NUM_THREADS=$threads
MKL_NUM_THREADS=$threads
OPENBLAS_NUM_THREADS=$threads
NUMEXPR_NUM_THREADS=$threads
UVICORN_WORKERS=1
OLLAMA_NUM_PARALLEL=$parallel
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_KEEP_ALIVE=30m
"@ | Set-Content -Path $WriteEnv -Encoding UTF8

    Write-Host "✅ Wrote CPU profile: $WriteEnv"
}

Write-Host "💡 Tip: përdor model quantized (q4_K_M / q5_K_M) për performancë më të mirë pa GPU."
