#!/usr/bin/env bash
set -euo pipefail

# CPU-only tuning helper for Ollama + Python services
# Usage:
#   bash scripts/cpu_boost_no_gpu.sh
#   bash scripts/cpu_boost_no_gpu.sh --write-env .env.cpu.local

WRITE_ENV=""
if [[ "${1:-}" == "--write-env" ]]; then
  WRITE_ENV="${2:-.env.cpu.local}"
fi

if command -v nproc >/dev/null 2>&1; then
  CORES="$(nproc)"
else
  CORES=4
fi

if [[ "$CORES" -le 2 ]]; then
  THREADS=1
  PARALLEL=1
elif [[ "$CORES" -le 8 ]]; then
  THREADS=$((CORES - 1))
  PARALLEL=1
else
  THREADS=$((CORES - 2))
  PARALLEL=2
fi

if [[ "$THREADS" -lt 1 ]]; then THREADS=1; fi

cat <<EOF
🔧 CPU-Only tuning profile
  cores:                 $CORES
  worker threads:        $THREADS
  ollama parallel req:   $PARALLEL

Export these variables in your shell/session:
  export OMP_NUM_THREADS=$THREADS
  export MKL_NUM_THREADS=$THREADS
  export OPENBLAS_NUM_THREADS=$THREADS
  export NUMEXPR_NUM_THREADS=$THREADS
  export UVICORN_WORKERS=1
  export OLLAMA_NUM_PARALLEL=$PARALLEL
  export OLLAMA_MAX_LOADED_MODELS=1
  export OLLAMA_KEEP_ALIVE=30m
EOF

if [[ -n "$WRITE_ENV" ]]; then
  cat > "$WRITE_ENV" <<ENVFILE
# Auto-generated by scripts/cpu_boost_no_gpu.sh
OMP_NUM_THREADS=$THREADS
MKL_NUM_THREADS=$THREADS
OPENBLAS_NUM_THREADS=$THREADS
NUMEXPR_NUM_THREADS=$THREADS
UVICORN_WORKERS=1
OLLAMA_NUM_PARALLEL=$PARALLEL
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_KEEP_ALIVE=30m
ENVFILE
  echo "✅ Wrote CPU profile: $WRITE_ENV"
fi

echo "💡 Tip: përdor model quantized (p.sh. q4_K_M / q5_K_M) për fitim real pa GPU."
